name: Cleanup

on:
  schedule:
    - cron: '56 17 * * *' # every day at 5:56pm UTC

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '2 days'    # delete artifacts older than this
          skip-tags: false # don't treat artifacts created by runs on tagged commits differently
          skip-recent: 1   # keep the latest run, regardless of age
